---
- name: Join domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_join

- name: Reboot after joining domain if it is needed
  win_reboot:
  when: domain_join.reboot_required
