---
- name: Include vault
  include_vars: vault.yml

- name: Create Admin user
  win_user:
    name: "{{ admin_username }}"
    password: "{{ admin_password }}"
    state: present
    groups:
      - Administrators

- name: Hide admin user from logon screen
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinLogon\SpecialAccounts\UserList
    name: "{{ admin_username }}"
    type: dword
    data: 00000000
