---
- name: Optimize powershell
  win_shell: |
    function Optimize-PowershellAssemblies {
      # NGEN powershell assembly, improves startup time of powershell by 10x
      $old_path = $env:path
      try {
        $env:path = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
        [AppDomain]::CurrentDomain.GetAssemblies() | % {
          if (! $_.location) {continue}
          $Name = Split-Path $_.location -leaf
          if ($Name.startswith("Microsoft.PowerShell.")) {
            Write-Progress -Activity "Native Image Installation" -Status "$name"
            ngen install $_.location | % {"`t$_"}
          }
        }
      } finally {
        $env:path = $old_path
      }
    }
    Optimize-PowershellAssemblies

- name: Disable PasswordComplexity
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0

- name: Add groups
  community.windows.win_domain_group:
    name: "{{ item }}"
    scope: global
    state: present
  loop: "{{ domain_groups }}"

- name: Add users
  community.windows.win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    password_never_expires: true
    state: present
  loop: "{{ domain_users }}"
