---
timezone: Iran Standard Time
admin_username: aminvakil
admin_password: "{{ admin_password }}"
kms_server: kms.microsoft.com
region_format: fa-IR
region_location: 116
region_unicode_language: fa-IR
